// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: factor/factorpb/factor.proto

package factorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FactorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputNumber int32 `protobuf:"varint,1,opt,name=inputNumber,proto3" json:"inputNumber,omitempty"`
}

func (x *FactorRequest) Reset() {
	*x = FactorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_factor_factorpb_factor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorRequest) ProtoMessage() {}

func (x *FactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_factor_factorpb_factor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorRequest.ProtoReflect.Descriptor instead.
func (*FactorRequest) Descriptor() ([]byte, []int) {
	return file_factor_factorpb_factor_proto_rawDescGZIP(), []int{0}
}

func (x *FactorRequest) GetInputNumber() int32 {
	if x != nil {
		return x.InputNumber
	}
	return 0
}

type FactorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FactorResponse) Reset() {
	*x = FactorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_factor_factorpb_factor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorResponse) ProtoMessage() {}

func (x *FactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_factor_factorpb_factor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorResponse.ProtoReflect.Descriptor instead.
func (*FactorResponse) Descriptor() ([]byte, []int) {
	return file_factor_factorpb_factor_proto_rawDescGZIP(), []int{1}
}

func (x *FactorResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_factor_factorpb_factor_proto protoreflect.FileDescriptor

var file_factor_factorpb_factor_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x70,
	0x62, 0x2f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x31, 0x0a, 0x0d, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x0e, 0x46, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0x4c, 0x0a, 0x0d, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x15,
	0x2e, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x46,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x11, 0x5a, 0x0f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x66, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_factor_factorpb_factor_proto_rawDescOnce sync.Once
	file_factor_factorpb_factor_proto_rawDescData = file_factor_factorpb_factor_proto_rawDesc
)

func file_factor_factorpb_factor_proto_rawDescGZIP() []byte {
	file_factor_factorpb_factor_proto_rawDescOnce.Do(func() {
		file_factor_factorpb_factor_proto_rawDescData = protoimpl.X.CompressGZIP(file_factor_factorpb_factor_proto_rawDescData)
	})
	return file_factor_factorpb_factor_proto_rawDescData
}

var file_factor_factorpb_factor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_factor_factorpb_factor_proto_goTypes = []interface{}{
	(*FactorRequest)(nil),  // 0: factor.FactorRequest
	(*FactorResponse)(nil), // 1: factor.FactorResponse
}
var file_factor_factorpb_factor_proto_depIdxs = []int32{
	0, // 0: factor.FactorService.Factor:input_type -> factor.FactorRequest
	1, // 1: factor.FactorService.Factor:output_type -> factor.FactorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_factor_factorpb_factor_proto_init() }
func file_factor_factorpb_factor_proto_init() {
	if File_factor_factorpb_factor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_factor_factorpb_factor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_factor_factorpb_factor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_factor_factorpb_factor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_factor_factorpb_factor_proto_goTypes,
		DependencyIndexes: file_factor_factorpb_factor_proto_depIdxs,
		MessageInfos:      file_factor_factorpb_factor_proto_msgTypes,
	}.Build()
	File_factor_factorpb_factor_proto = out.File
	file_factor_factorpb_factor_proto_rawDesc = nil
	file_factor_factorpb_factor_proto_goTypes = nil
	file_factor_factorpb_factor_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FactorServiceClient is the client API for FactorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FactorServiceClient interface {
	Factor(ctx context.Context, in *FactorRequest, opts ...grpc.CallOption) (FactorService_FactorClient, error)
}

type factorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFactorServiceClient(cc grpc.ClientConnInterface) FactorServiceClient {
	return &factorServiceClient{cc}
}

func (c *factorServiceClient) Factor(ctx context.Context, in *FactorRequest, opts ...grpc.CallOption) (FactorService_FactorClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FactorService_serviceDesc.Streams[0], "/factor.FactorService/Factor", opts...)
	if err != nil {
		return nil, err
	}
	x := &factorServiceFactorClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FactorService_FactorClient interface {
	Recv() (*FactorResponse, error)
	grpc.ClientStream
}

type factorServiceFactorClient struct {
	grpc.ClientStream
}

func (x *factorServiceFactorClient) Recv() (*FactorResponse, error) {
	m := new(FactorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FactorServiceServer is the server API for FactorService service.
type FactorServiceServer interface {
	Factor(*FactorRequest, FactorService_FactorServer) error
}

// UnimplementedFactorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFactorServiceServer struct {
}

func (*UnimplementedFactorServiceServer) Factor(*FactorRequest, FactorService_FactorServer) error {
	return status.Errorf(codes.Unimplemented, "method Factor not implemented")
}

func RegisterFactorServiceServer(s *grpc.Server, srv FactorServiceServer) {
	s.RegisterService(&_FactorService_serviceDesc, srv)
}

func _FactorService_Factor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FactorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FactorServiceServer).Factor(m, &factorServiceFactorServer{stream})
}

type FactorService_FactorServer interface {
	Send(*FactorResponse) error
	grpc.ServerStream
}

type factorServiceFactorServer struct {
	grpc.ServerStream
}

func (x *factorServiceFactorServer) Send(m *FactorResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _FactorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "factor.FactorService",
	HandlerType: (*FactorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Factor",
			Handler:       _FactorService_Factor_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "factor/factorpb/factor.proto",
}
